#!/bin/bash
#set -ex
# Linux bash script to browse all domains, subdomains, addon domains hosted on local cPanel server.
# It will create webpage on local webpath which will include clickable list of all mentioned sites and exclude sites in default state (empty Index Of page), suspended or pointed to different server
# The list of hosted sites will also include cpanel username, e-mail and a few interesting php files or folders in the users path so admin can examine what is hosted
# The suspended, excluded cpanels and its sites should not be included in the list also those that not uploaded any files will be excluded
# AIM OF THE SCRIPT is to help admin see new sites, browse them to see if there is no TOS violating content

# local full web path to .php or .htm/l file where to store clickable list of hosted sites
weblist=/home/usernemehere/public_html/privatedirname/localsites.php
webacctusr=usernemehere
# exclude sites of certain users, NO spaces
excludedcpanels="abcd,efgh"

# admin e-mail on which will be reported Google's Safe Browsing listed site (bad site)
adminmaill=admin@mail

# Delay in seconds to wait before third party safebrowsing check site is queried to be polite and safe
sleepsafebrowscheck=8

# If new hosting accounts on your server contains any files like robots.txt, you should enter it here. We exclude sites that do not contain any other files/are in default state
filesonindexof="cgi-bin|favicon.ico|robots.txt"

# excluded files when listing www directory contents of a cpanel
excludedfiles=".jpg|.png|.gif|.txt|.xml|.csv|.shtml|error_log|cgi_bin|htaccess|favicon|wp-|.ini|.db"

# directory where this bash script is located
thisscriptdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# this server IP
localip=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')

# discover suspended cpanels
suspended_cpanels=$(ls -A1 /var/cpanel/suspended)

# domains and its users
domains_and_users=$(cat /etc/domainusers)

# ---------------- no need to further edit below this line -------------------------------

# erase files to prevent duplicity from previous run
> $weblist

echo "Site list last updated <strong>$(date)</strong> by $thisscriptdir/ and sitelist does not contain admin excluded, suspended, not resolving to $(hostname) sites (cloudflare). Last serv. bckp: $(ls -lht /backup/|head -n3|tail -n1)<br>" >> $weblist

sitesnumber="$(cat /etc/localdomains|wc -l)" && echo "There is $sitesnumber sites"

i=0
for site in $(cat /etc/localdomains);do
i=$[$i+1]

siteuser=$(/scripts/whoowns $site)

# exclude sites of certain users
if [[ "$(echo $excludedcpanels)" == *"$siteuser"* ]];then
echo "Excluding site as its owner is on blacklist/excluded: $site ($i/$sitesnumber)"
# skip to next site
continue
fi

for ip in $(echo "$localip");do
if [[ "$(host $site)" == *"$ip"* ]];then
icphresolving=1
fi
done

# "good, site points to this server, but lets check if its not suspended. If it is, then continue with next site."
if [[ "$(echo "$suspended_cpanels")" == *"$siteuser"* ]];then
echo "site is suspended so i dont care about it, do not add it into the list, skip to next one"
continue
fi

sitecontent="$(curl --silent --max-time 5 "$site")"
sleep 3

# If website contains no index, Index of page is shown. If this page is empty or contains only defaut files, we skip such site
sitecontentlines=$(echo "$sitecontent"|grep -vE "$filesonindexof"|wc -l)
# in following condition we examine index page source code is worth n lines to better measure the site is really a default page and be excluded
if [[ "$sitecontent" == *"Index of"* && "$sitecontentlines" == "9" ]];then
echo "Site is in default state/has no index, no files, im not interested in this site to be listed, skip. $site ($i/$sitesnumber)"
# skip to next site
continue
fi
echo "Site is in modiffied state, will be reported: $site ($i/$sitesnumber)"

# "Adding site to the active list"
if [[ "$icphresolving" == "1" ]];then
echo "<strong><a href=\"http://$site\" target=\"_blank\">http://$site</a></strong> - A few cPanel <strong>$siteuser</strong> / $(cat /var/cpanel/users/$siteuser|grep CONTACTEMAIL=|cut -c 14-) items: $(ls -m --group-directories-first /home/$siteuser/public_html/|grep -vE \"$excludedfiles\"|head -1)<br />" >> $weblist
fi

done
chown $webacctusr:$webacctusr $weblist
exit
# REST IS DISABLED AS WHITEFIRDESIGN BLCOKED MY IP PROBABALY

#### Optional check against google safebrowsing database of bad sites

if [[ "$site" == *"."* ]];then
sleep $sleepsafebrowscheck
output="$(timeout 30 curl --silent https://www.whitefirdesign.com/tools/google-safe-browsing-check.html?address="$site")"
if [[ "$output" == *"Google"* ]];then
# Good, page is likely valid, no 404, 301 page or such
if [[ "$output" != *"Google does not currently report that"* ]];then
echo "Domain $site (http://$site) is listed in Google Safe Browsing DB:
https://www.whitefirdesign.com/tools/google-safe-browsing-check.html?address=$site
https://www.google.com/transparencyreport/safebrowsing/diagnostic/index.html#url=$site

This is /root/scripts/all*/get* from $(hostname)"|mail -s "Hosted site is on GSB list" -- $adminmaill
fi
else
echo -e "Strange, the curl output might be something strange. Edit curl URL in /root/scripts/all*/\nOutput:\n\"$output\""|mail -s "Some error in the getsitelist script" $adminmaill
exit
fi
else
echo "Strange, the site variable not contained dot. Site: $site
This is /root/scripts/all*/"|mail -s "Some error in the script" $adminmaill
fi

######  end of check
